/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef DPIEXT_AUTODEFS_H
#define DPIEXT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_DPIEXT_NAME "dpiExt"
#define S3E_EXT_DPIEXT_HASH 0xf948ed73

#endif /* !DPIEXT_AUTODEFS_H */
