/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"

#include "dpiExt.h"

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef        int(*dpiExtGetDeviceDPI_t)();

/**
 * struct that gets filled in by dpiExtRegister
 */
typedef struct dpiExtFuncs
{
    dpiExtGetDeviceDPI_t m_dpiExtGetDeviceDPI;
} dpiExtFuncs;

static dpiExtFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xf948ed73, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE, "error loading extension: dpiExt");
        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xf948ed73, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool dpiExtAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

int dpiExtGetDeviceDPI()
{
    IwTrace(DPIEXT_VERBOSE, ("calling dpiExt[0] func: dpiExtGetDeviceDPI"));

    if (!_extLoad())
        return -1;

    return g_Ext.m_dpiExtGetDeviceDPI();
}
