/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "dpiExt_autodefs.h"
#include "s3eEdk.h"
#include "dpiExt.h"
//Declarations of Init and Term functions
extern s3eResult dpiExtInit();
extern void dpiExtTerminate();


#if defined I3D_OS_IPHONE || defined I3D_OS_OSX

static int dpiExtGetDeviceDPI_wrap()
{
    IwTrace(DPIEXT_VERBOSE, ("calling dpiExt func on main thread: dpiExtGetDeviceDPI"));
    return (int)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)dpiExtGetDeviceDPI, 0);
}

#define dpiExtGetDeviceDPI dpiExtGetDeviceDPI_wrap

#endif /* I3D_OS_IPHONE */

void dpiExtRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[1];
    funcPtrs[0] = (void*)dpiExtGetDeviceDPI;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[1] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("dpiExt", funcPtrs, sizeof(funcPtrs), flags, dpiExtInit, dpiExtTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int dpiExtStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&dpiExtRegisterExt;
    return 0;
}

int g_dpiExtVal = dpiExtStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    dpiExtRegisterExt();
}
#endif

#endif
